### ISSUE TITLE
error with vite

### ISSUE THREAD

**Issue by softboy99** [sandanat/vue-pdf-app#10]
inherits.js:4 Uncaught TypeError: Super expression must either be null or a function
    at _inherits (inherits.js:4)
    at pdf-viewer.vue?c8a8:912
    at Module.fb15 (pdf-viewer.vue?c8a8:912)
    at __webpack_require__ (bootstrap:19)
    at 0 (bootstrap:83)
    at bootstrap:83
    at webpackUniversalModuleDefinition (universalModuleDefinition:3)
    at universalModuleDefinition:9
    at chunk.2VCUNPV2.js?v=7252826d:4
    at dep:vue-pdf-app:1
_inherits @ inherits.js:4
(anonymous) @ pdf-viewer.vue?c8a8:912
fb15 @ pdf-viewer.vue?c8a8:912
__webpack_require__ @ bootstrap:19
0 @ bootstrap:83
(anonymous) @ bootstrap:83
webpackUniversalModuleDefinition @ universalModuleDefinition:3
(anonymous) @ universalModuleDefinition:9
(anonymous) @ chunk.2VCUNPV2.js?v=7252826d:4
(anonymous) @ dep:vue-pdf-app:1

**Comment by sandanat** [comment]
Provide a demo with steps to reproduce please

**Comment by softboy99** [comment]
step to reproduce:
1、npm init @vitejs/app my-vue-app -- --template vue
2、add the basic sample code in readme.md to app.vue:

<template>
  <pdf-viewer pdf="http://example.com/sample.pdf"></pdf-viewer>
</template>

<script>
import PdfViewer from "vue-pdf-app";

export default {
  components: {
    PdfViewer
  }
}
</script>


3、run

**Comment by softboy99** [comment]
I guess the problem would be your code is based on vue2. It failed in vue3 for the "extend Vue"

**Comment by sandanat** [comment]
Yes, current package has incomitible code with Vue 3.
I am going to implement several features for this package and after that I try to create pdf viewer for Vue 3.
I hope it happens this summer.
