### ISSUE TITLE
Global styles manipulate styles of website 

### ISSUE THREAD

**Issue by Alexxk1982** [sandanat/vue-pdf-app#11]
Hi, the global styles e.g. in viewer.css are changing styles of other vue elements outside of your component. (*, html, body, input, button, select,.. which are defined in your viewer.css) Please restrict them to your own container.. e.g. with a custom class on your main container?! Or you could use a shadow dom? Thanks! :)

**Comment by Alexxk1982** [comment]
Sorry the global styles are from pdfjs viewer 😏

**Comment by armie-isla** [comment]
Do you have any workaround for this issue or can you recommend other libraries?

**Comment by sandanat** [comment]
I will fix it this weekend

Other libraries: https://github.com/vuejs/awesome-vue#pdf

  
>Четверг, 25 февраля 2021, 10:55 +03:00 от armie-isla <notifications@github.com>:
> 
> 
>Do you have any workaround for this issue or can you recommend other libraries?
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
-----------------------------------------------
С уважением, Андрей Сергеев
e-mail: adid62@mail.ru

**Comment by aislaapps** [comment]
Thank you
