### ISSUE TITLE
PDF not displayed when <pdf-app> is placed under a <div> element

### ISSUE THREAD

**Issue by jan-kacina** [sandanat/vue-pdf-app#14]
Hi @sandanat ,
I've spent a lot of hours to determine, what's the reason of not displaying PDF viewer in my Vue app. If you have any workaround for thiss issue, please provide.

**Configuration:**

- Web browser and it`s version: Firefox 86, Chrome 89
- Operating system and it`s version: Windows 10
- vue-pdf-app version: 1.0.1

**Steps to reproduce the problem:**

1. Use [Typescript Example](https://github.com/sandanat/vue-pdf-app/tree/master/examples/typescript)
2. In `src/App.vue` place `<pdf-app>`  element into additional `<div>` element like this:
```
<template>
  <div id="app">
    <div>
      <pdf-app pdf="/sample.pdf"></pdf-app>
    </div>
  </div>
</template>
```
3. Build and run application, e.g. `npm run serve`
4. Display application in browser

**What is the expected behavior?**
A PDF is displayed together with top menu.

**What went wrong?**
PDF and menu are not displayed. No error in console.
This issue completely prevents to use `vue-pdf-app` inside a Vue / Vuetify element which internaly creates `<div>` element.

**Comment by sandanat** [comment]
Hi, you have to specify a height of your div-wrapper:

![image](https://user-images.githubusercontent.com/49751869/110623681-3b0e0800-81ae-11eb-9c76-d02cac2ca3bd.png)

**Comment by jan-kacina** [comment]
Not very nice, but functional workaround. In general, it requires to add `style="height: 100%;"` to all `<div>` predecessors.
In my case it's 4-level hierarchy, incl. Vuetify's `<v-tab-items>` and `<v-tab-item>`.

Do you know what's the main reason for such behavior? Is it related to Mozilla's PDFJS or to your implementation?

Thanks a lot.

**Comment by sandanat** [comment]
It is not necessary to specify height of every predecessor. If you know the desired height of pdf you can specify it directly like this:
```html
<div id="app">
  <div>
    <div>
      <div>
        <pdf-app style="height: 100vh;"></pdf-app>
      </div>
    </div>
  </div>
</div>
```

[Example](https://codepen.io/sandanat/pen/xxVdgYM)
This is my implementation. The reason is that a size of the pdf must be controlled in parent. Otherwise scrollbar can appear for example, as in the provided example.

You can provide your solution. I will implement it if it`s Ok.

**Comment by jan-kacina** [comment]
I consider this as solved - suggestion with `style="height: 100vh;"` works well. 

Thanks for explanation.

**Comment by parmsnapsuite** [comment]
what if the pdf is inside the modal? and my modal is just half of the window size, applying 100vh makes the pdf go beyond the modal height.
