### ISSUE TITLE
Opening pdf in modal dialogue giving error 

### ISSUE THREAD

**Issue by rutup** [sandanat/vue-pdf-app#16]
Hi I need help on following. Not sure if it is bug or there is correction needed in my code.

I am opening dialog and inside that trying to show pdf as shown in **PDFJS interaction  example**. It returns error
as follow 

![image](https://user-images.githubusercontent.com/5991399/111142992-506aa400-85ab-11eb-86d6-d5c97ce4270d.png)
 
Url of pdf is being set at runtime on mounted function of dialog. Dialog is added in parent page as below
```
 <details
      v-show="isModalVisible" v-bind:id="invoiceId"
      @close="closeModal"
    />
```
and its being shown by following code
```
 showModal() {
      this.isModalVisible = true;
    },
```

**Comment by sandanat** [comment]
Hi!
Can you provide a repo with this issue or full code of your component? It works fine with primevue dialog ([example](https://codesandbox.io/s/vue-pdf-app-in-dialog-9u8d3?file=/src/App.vue))
Does the error occur during the first dialog opening?
Does it a dialog or a detail tag?

Try something listed below:
1. Remove all props from pdf just to see if it works fine
2. Use `v-if` for pdf linked to `isModalVisible` variable `<pdf v-if="isModalVisible pdf="link.pdf"></pdf>`
3. If a dialog has after-open event handler, try to add this method
```javascript
async afterOpenDialog() {
  await this.$nextTick();
  this.pdfLink = "link-to-the-pdf.pdf"
}
```

**Comment by rutup** [comment]
console error stopped logging once i wrote 
```
v-if="isModalVisible
```
also wanted to check does this component support IE 11 ? as there is no documentation around it. It just mentions cross browser support

**Comment by sandanat** [comment]
Yes, IE11 is supported
