### ISSUE TITLE
Call openhandler function programmatically 

### ISSUE THREAD

**Issue by rutup** [sandanat/vue-pdf-app#22]
I am fetching pdf from API then saving it on some path.
based on API result I need to load PDF i.e. dynamically. I tried setting file name at run time and this is changing page title.
I know page title can be changed in **OpenHandler** function. But not sure how to  call it programmatically. If there is workaround for it Let me know

**Comment by sandanat** [comment]
Hi, refer this [example](https://github.com/sandanat/vue-pdf-app/blob/master/examples/pdfjs-interaction/src/App.vue#L35).
This also can be done in a more convenient way with [future release ](https://github.com/sandanat/vue-pdf-app/tree/develop#after-createdpdfviewerapplication)

**Comment by rutup** [comment]
thanks this sample gave me idea to hold the title and fix the current issue. Also just to let you know there seems to be issue related to page title. Placing scenario below.
set PDF URL after API call and then **openhandler** gets called it tries to set page title at that time again and it is not document name. it is something else
