### ISSUE TITLE
Jump to page 

### ISSUE THREAD

**Issue by iglimanaj** [sandanat/vue-pdf-app#23]
Hello,

I was wondering if there is any possibility to jump to a specific page of the pdf. Is there any property for setting the page?

Thanks!

**Comment by sandanat** [comment]
Hi
```vue
<vue-pdf @open="open" />
```
```js
open(pdfApp) {
     setTimeout(() => {
        pdfApp.page = 31;
      });
}
```

**Comment by iglimanaj** [comment]
Thanks for the quick response! It seems to work :D

**Comment by iglimanaj** [comment]
Hi the open event is being invoked during the initial opening of the pdf. Is it possible to interact with an already opened pdf? I would be interested if one can jump from one page to another after the pdf document is opened.

**Comment by sandanat** [comment]
Hi!
Why don't you use a default toolbar functionality? Feedback is wellcome, it helps me to improve the package.
You can do this:
```vue
<template>
  <div style="height: 90%">
    <input v-model.number="pageNumber" type="text" />
    <button @click="jumpToPage" type="button">Jump to page</button>
    <vue-pdf-app @open="openHandler" pdf="sample.pdf"></vue-pdf-app>
  </div>
</template>

<script>
import VuePdfApp from "vue-pdf-app";

export default {
  components: {
    VuePdfApp,
  },
  data() {
    return {
      pageNumber: 1,
    };
  },
  methods: {
    openHandler(pdfApp) {
      // non-reactive
      this.pdfApp = pdfApp;
    },

    jumpToPage() {
      this.pdfApp.page = this.pageNumber;
    },
  },
};
</script>
```

Also refer this note about [reactivity](https://github.com/sandanat/vue-pdf-app/blob/develop/FAQ.md#can-i-interract-with-mozillas-pdfjs-library-outside-the-event-handlers-of-pdf-viewer)

**Comment by sandanat** [comment]
@iglimanaj, do you have any other questions? Can I close the issue?
