### ISSUE TITLE
is there any way to stop editing page title  by default 

### ISSUE THREAD

**Issue by rutup** [sandanat/vue-pdf-app#24]
is there any way to stop editing page title  by default.  It can be changed by **openhandler** but any setting which **disable** default page title set shall be helpful. as changing it in **openhandler** creates flicker and also for fraction of second it shows default name.

I tried ` PDFViewerApplication.setTitle(this.pageTitle);   
        PDFViewerApplication.isViewerEmbedded = true;` but it doesn't help

**Comment by sandanat** [comment]
`isViewerEmbedded` will help in future release [v2.0.0](https://github.com/sandanat/vue-pdf-app/milestone/1) (coming in a few weeks) like shown in this [sample](https://github.com/sandanat/vue-pdf-app/blob/develop/examples/the-most-complete-example/src/views/PdfjsInteraction.vue#L34). 
And a flicker doesn't occur in it.

**Comment by sandanat** [comment]
Done in v2.0
