### ISSUE TITLE
Feature Proposal

### ISSUE THREAD

**Issue by iglimanaj** [sandanat/vue-pdf-app#29]
Hi, 
I am using the pdf viewer as an integrated component in a web app and I have noticed that the tab name is automatically updated to the title of the pdf file when it is rendered by the pdf-viewer-app component. 

How about a config to disable this automatic update?

Best regards!
Igli

**Comment by iglimanaj** [comment]
redundant proposal,  #24 :D

**Comment by sandanat** [comment]
Hi!
Ok, I will disable title rename by default as too many requests about that.
Await v2.0

**Comment by sandanat** [comment]
Done in v2.0
