### ISSUE TITLE
Buttons not visible

### ISSUE THREAD

**Issue by iglimanaj** [sandanat/vue-pdf-app#33]
Hi Andrey,

I switched to the latest version and noticed that the buttons are not visible any more. They are still there and function if I click on them, but they are not visible. Here you can find a screenshot.

If you have any idea, where the problem might be, I could also contribute on fixing.

![image](https://user-images.githubusercontent.com/12574741/112635626-54fd4b00-8e3c-11eb-8c15-bf87cd519aec.png)

**Comment by sandanat** [comment]
Hi! You have to `import "vue-pdf-app/dist/icons/main.css";`
For breaking changes refer [CHANGELOG.md](https://github.com/sandanat/vue-pdf-app/blob/master/CHANGELOG.md)

**Comment by iglimanaj** [comment]
Thanks! You are doing a great work btw!

**Comment by sandanat** [comment]
Thank you!
