### ISSUE TITLE
What's the best way to call the `pages-rendered` event one the browser window is resized?

### ISSUE THREAD

**Issue by 949mac** [sandanat/vue-pdf-app#36]
Basically, I've dropped an overlay image on my pdf. It's placed nicely relative, and to scale. But when I resize, my overlay disappears.

If I refresh my app, the overlay returns and remains in the proper position.

I feel like a  resize event passing the `PDFViewerApplication` would solve this, unless I'm missing another way.

Great package, btw. 👍

**Comment by sandanat** [comment]
Hi!
Thank you for your praise!
Sorry, but I didn't understand an essence of the problem clearly. This would be great if you provide a working example with your issue.

`pages-rendered` event is emitted when `PDFViewerApplication.pdfViewer.pagesPromise` is fulfilled. And this promise doesn't change it's state during window resize event. So it has no sense in your case.

If you just want to pass `PDFViewerApplication` to window resize event you can do it in `after-created` event:
```vue
<template>
  <vue-pdf-app @after-created="afterCreatedHandler"></vue-pdf-app>
</template>

<script>
export default {
  methods: {
    afterCreatedHandler(pdfApp) {
      const func = (pdfApp) => {
         // may be this can help
         pdfApp.forceRendering();
      };

      // use underscore or lodash debounce to avoid intermediate resize and increase performance
      const debounced = lodash.debounce(func, 2000, { trailing: true });

      window.addEventListener("resize", debounced);

      // don't forget to unbind handler on component destroy
      this.$once("hook:beforeDestroy", () => {
        window.removeEventListener("resize", debounced);
      });
    },
  },
};
</script>
```

You can also use resize libraries ([vue-resize-sensor](https://www.npmjs.com/package/vue-resize-sensor) for instance). You have to bind `PDFViewerApplication` to a parent component like [described here](https://github.com/sandanat/vue-pdf-app/blob/master/FAQ.md#can-i-interract-with-mozillas-pdfjs-library-outside-the-event-handlers-of-pdf-viewer):
```vue
<resize-sensor @resize="resize">
  <vue-pdf-app></vue-pdf-app>
</resize-sensor>

methods: {
  resize() {
    this.pdfApp.forceRendering();
  },
}
```

I can explore further if you provide a working example with your issue.

**Comment by sandanat** [comment]
@949mac, do you have any other questions? Can I close the issue?
