### ISSUE TITLE
 I want to change the language.

### ISSUE THREAD

**Issue by 283po1** [sandanat/vue-pdf-app#37]
The technology set is es5(js), vue2

English is the default language for panel. Use <link rel="resource" type="application/l10n" href="path-to-localization-file"> in your html for localization. See localization file examples.

The above doesn't make sense.

Create locale.ts for 'ko' by referring to the contents of 'ko' of the address(https://github.com/mozilla/pdf.js/tree/master/l10n ) and in index.html <link rel="resource" type="application/l10n" href="../src/assets/locale.ts">
Can I put it on?

Locale.ts i made
```
/* eslint-disable @typescript-eslint/camelcase */
export default {
  default_locale: "ko",
  locales: {
    ko: {
      zoom_out: {
        title: "줌 아웃"
      },
      zoom: {
        title: "줌"
      }
    }
  }
};
```
If you do as above,'zoom is undefined' is displayed on the console. 
All items are undefined.

Finally, how do I set l10n to ko in Vue? Is it possible to access webL10n and set it to setLanguage('ko')?

I'm sorry that I don't seem to know too much.

**Comment by sandanat** [comment]
Hi!
1. Take a desired locale [from here](https://github.com/mozilla/pdf.js/blob/master/l10n/ko/viewer.properties)
2. Copy paste it into a file in your project (*locale.txt* for instance)
3. Add `<link rel="resource" type="application/l10n" href="path-to-the-locale.txt" />` into your html

Example [is here](https://codesandbox.io/s/vue-pdf-app-9u8d3?file=/public/index.html:269-334)

![image](https://user-images.githubusercontent.com/49751869/113776657-ce494780-9732-11eb-8b60-fdcd15049de0.png)

**Comment by sandanat** [comment]
@283po1, do you have any other questions? Can I close the issue?

**Comment by mengfanyin** [comment]
Add  `<link rel="resource" type="application/l10n" href="locale" /> `

it still not work.

```
#thumbs is undefined.
...
#thumbs_label is undefined.
....
#document_outline_label is undefined.
......
```

**Comment by kennycreeper** [comment]
@mengfanyin Maybe it's because the version of i10n file you used is incompatible. I use older version and it's works!
