### ISSUE TITLE
Nuxt support?

### ISSUE THREAD

**Issue by ManasMadrecha** [sandanat/vue-pdf-app#39]
**Please describe a feature/problem.**
To be able to use on Nuxt

**Describe the solution you'd like**
An example on `readme` file how to use it on Nuxt

**Comment by ManasMadrecha** [comment]
## What I tried (and didn't work) in Nuxt app.
My PDF file is saved in `static` folder, so it's accessible as `/book.pdf`.

### Trial 1
Created a `vue-pdf-app.js` under plugins folder.
```js
import Vue from 'vue'
import VuePdfApp from "vue-pdf-app";

Vue.component('VuePdfApp', VuePdfApp)
```
Then, I registered it in `nuxt-config.js` as:
```js

plugins: [
    { src: '~/plugins/vue-pdf-app.js', mode: 'client' },
  ],
```

Then, used it in normal `pages` folder inside `<template></template>`.
```vue
<vue-pdf-app pdf="/book.pdf"></vue-pdf-app>

<!-- or -->

<client-only>
<vue-pdf-app pdf="/book.pdf"></vue-pdf-app>
</client-only>

```

This should have worked as it usually works for any vue-plugin, but it didn't.

### Trial 2
I removed the plugin to avoid global registration, and tried importing the component inside one specific page.

I used the [Lazy Loading example on the readme file.](https://github.com/sandanat/vue-pdf-app/blob/master/README.md#lazy-loading).

So, inside my specific page's `export default`, I did this:

```vue
<script>
import "vue-pdf-app/dist/icons/main.css";
import tip from "~/components/tip.vue";

export default {
  components: {
    "vue-pdf-app": () => ({
      component: new Promise((res) => {
        return setTimeout(
          () => res(import(/* webpackChunkName: "pdf-viewer" */ "vue-pdf-app")),
          4000
        );
      }),
      loading: tip
    })
  }
};
</script>

```

**Several Errors inside console**: 
1. `TypeError: Cannot read property 'currentPageNumber' of null`
2. `TypeError: Cannot read property '_off' of null`
3. `using the embedded JSON directory, early way out`
4. `Warning: Setting up fake worker.`
5. And, then hundreds of times `TypeError: Cannot read property 'parentNode' of null`

### Trial 3
Changed syntax of component registration to load as async.

```
components: {
  VuePdfApp: () => import("vue-pdf-app")
}
```

**Error:** 

### Trial 4
Added `process.client` to import only on client side.

```
components: {
  VuePdfApp: () => (process.client ? import("vue-pdf-app") : "")
}
```

**Error**: same as Trial 2.

**Comment by fabricepallaud** [comment]
@ManasMadrecha did you manage to make it work with Nuxt eventually?

**Comment by ManasMadrecha** [comment]
@fabricepallaud 
Yes, I was able to do it with some of the above method. I think it was method 2, i.e. install as global plugin with `window.onNuxtReady` and register it as `ssr: false` in `nuxtconfig.js`. And I think this error `TypeError: Cannot read property 'currentPageNumber' of null` was due to the component unable to find the book. As soon as I entered the correct file path of a file stored in `static` folder, it worked great.

However, I was unable to import this component "dynamically" and this caused my website size to rise manifold (over 2-3MB). So, I am no longer using this nonetheless awesome component. 

I have moved on to using my PDF files from OneDrive; I simply embed the iframe thereof. And just to ensure that the iframe doesn't cause any delay in page size, I put it inside a normal html `<details>` tag.  😊 

**Benefits of OneDrive PDF viewer iframe**:
1. No need to keep the file and folder structure of the PDFs rigidly set in `static` folder
2. I find it more convenient to use already existing PDFs on my PC scattered anywhere, as my folder structure can then be anything I want as is set in my PC, and independent how one website uses it.
3. Use one PDF saved in OneDrive for multiple websites
4. Of course, OneDrive iframe doesn't give greater control over "find" and sidebar navigation, but still it looks decent with basic zoom options and page number and that's all I want for my current use case anyway.

Anyway, I read somewhere it's better to give the option of downloading the PDF rather than just display it inside HTML. So, a collapsible OneDrive PDF viewer and a download button works the best.

**Comment by sandanat** [comment]
Hi! I'll try to implement it in 3 weeks. It was a hard spring, sorry

**Comment by ManasMadrecha** [comment]
@sandanat Thanks, and it would be great if you could also add docs on how to load it dynamically in Nuxt. 😊 Loved the viewer btw.

**Comment by sandanat** [comment]
> What I tried (and didn't work) in Nuxt app.
My PDF file is saved in static folder, so it's accessible as /book.pdf.
Trial 1
Created a vue-pdf-app.js under plugins folder.

@ManasMadrecha, your **Trial 1** works fine. Pdf is invisible in your case because of parent container height is not specified.
Refer [example](https://github.com/sandanat/vue-pdf-app/tree/develop/examples/nuxt)

**Comment by sandanat** [comment]
PR #61

**Comment by eductivegmbh** [comment]
This has greatly helped. Thank you!
