### ISSUE TITLE
Initial zoom value

### ISSUE THREAD

**Issue by iglimanaj** [sandanat/vue-pdf-app#40]
By default the initially chosen zoom option is `Automatic Zoom` (https://github.com/sandanat/vue-pdf-app/blob/master/src/components/pdf-viewer.vue#L648)

Is there any way to set another default value instead?

**Comment by sandanat** [comment]
Hi!

See example in [FAQ](https://github.com/sandanat/vue-pdf-app/blob/master/FAQ.md#can-i-set-a-default-page-scale-when-a-pdf-document-is-opening)

I will implement this feature in the next release as too many requests about it
