### ISSUE TITLE
Korean text recognition problem

### ISSUE THREAD

**Issue by 283po1** [sandanat/vue-pdf-app#41]
PDFs in Korean text cannot be recognized. Is it possible to support it?

If not, where should I add the font?
![20210414_123941](https://user-images.githubusercontent.com/41983926/114663474-592ed100-9d35-11eb-82b5-21dd9ff4466e.png)

**Comment by sandanat** [comment]
Hi!
If you don't need a text layer (text selection with cursor) try to disable it in `v-on:open` handler:
```
open(pdfApp) {
      pdfApp.pdfViewer.textLayerMode = 0;
}
```

If it doesn't work or if you need a text layer try to download font:
```vue
<style>
@import url('path to the font of pdf');
</style>
```

If it doesn't work provide a working example with this issue please

**Comment by sandanat** [comment]
@283po1, do you have any other questions? Can I close the issue?
