### ISSUE TITLE
Setting pdf at run time

### ISSUE THREAD

**Issue by rutup** [sandanat/vue-pdf-app#42]
Hi
In my case pdf is being returned as blob from API. So PDF needs to be generated dynamically. How can this be achieved?

**Comment by sandanat** [comment]
Hi!
You have to convert blob into arrayBuffer
1. Change response type of your request to `arraybuffer` if it is possible
2. Or
```
methods: {
    async fetch() {
      const result = await fetch("/sample.pdf")
      const blob = await result.blob()
      this.pdf = await blob.arrayBuffer();
    }
}
```

**Comment by rutup** [comment]
Thanks I am also facing one more issue when I download the PDF it gives its name as document.pdf. Is there any way I can download it by its name.

**Comment by rutup** [comment]
I tried using 
```
 if (!result.hasOwnProperty('isError')) {
                    const fileURL = window.URL.createObjectURL(new Blob([result.data], { type: 'application/pdf' }));
                    this.pdfUrl = fileURL;
                    // window.URL.revokeObjectURL(fileURL);
                  }
```
but the file name in download is document.pdf while in server side file name is **test.pdf**

**Comment by sandanat** [comment]
```vue
<template>
  <vue-pdf-app @open="open"></vue-pdf-app>
</template>

<script>
  export default {
    methods: {
      open(pdfApp) {
        pdfApp.PDFViewerApplication.pdfDocument.getMetadata()
        .then(fileMetadata => {
          pdfApp.PDFViewerApplication.contentDispositionFilename =
            fileName;
        })
        .catch(console.error.bind(console))  
      }
    }
  }
</script>
```

Details are [here](https://github.com/sandanat/vue-pdf-app/pull/34)

**Comment by rutup** [comment]
Thanks 
It works perfect. Just to mention not sure if this is right place in same issue should I write it or not. I am getting following message in browser 
```
pdf-viewer.umd.js?9b1a:45187 PDF 4d6f6e6461792c20417072696c2031322c203230323131313a35393a303620414d [1.6 Telerik Reporting 14.1.20.513 (http://www.telerik.com/products/reporting.aspx) /    Telerik Reporting 14.1.20.513 (http://www.telerik.com/products/reporting.aspx)] (PDF.js: 2.4.456)


```

**Comment by sandanat** [comment]
It is not an error. It is mozilla's [log message](https://github.com/sandanat/vue-pdf-app/blob/master/src/pdfjs-dist/lib/web/app.js#L1011)

**Comment by rutup** [comment]
Yes it is not an error but it is annoying if any one opens dev tools so , Is there any way that I can stop showing it on console

**Comment by sandanat** [comment]
Ok, I will fix it

**Comment by rutup** [comment]
Thanks waiting for disabling this logging for now closing issue

**Comment by irzafaikar** [comment]
> ```
> <template>
>   <vue-pdf-app @open="open"></vue-pdf-app>
> </template>
> 
> <script>
>   export default {
>     methods: {
>       open(pdfApp) {
>         pdfApp.PDFViewerApplication.pdfDocument.getMetadata()
>         .then(fileMetadata => {
>           pdfApp.PDFViewerApplication.contentDispositionFilename =
>             fileName;
>         })
>         .catch(console.error.bind(console))  
>       }
>     }
>   }
> </script>
> ```
> 
> Details are [here](https://github.com/sandanat/vue-pdf-app/pull/34)



I'm sorry. I get this error.

[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'pdfDocument' of undefined"

When i do this.. 
console.log(pdfApp.PDFViewerApplication);

return value is undefined

**Comment by sandanat** [comment]
Yes, `pdfApp.PDFViewerApplication` can be null in some cases. So you have to check `if (pdfApp.PDFViewerApplication) {...}` before operate it. Or use `pages-rendered` event. *pdfApp.PDFViewerApplication* has to be always defined during this event

**Comment by sandanat** [comment]
feef52f8c2fa4a94263ab1837200d9a701f3b90e
