### ISSUE TITLE
PDF Blank

### ISSUE THREAD

**Issue by irzafaikar** [sandanat/vue-pdf-app#44]
#### Configuration:
- Google Chrome 88.0.4324.150
- Ubuntu 20.10
- vue-pdf-app latest version

#### Steps to reproduce the problem:
Only follow the example in github.

#### What is the expected behavior?
PDF will show in the browser.

#### What went wrong?
PDF not showing. But its load in network tab.

#### Attachments (screenshots, links, etc)
![Screenshot from 2021-04-21 13-56-23](https://user-images.githubusercontent.com/54936003/115510291-bda7de00-a2a9-11eb-9916-736ae9e72a3a.png)
![Screenshot from 2021-04-21 13-55-14](https://user-images.githubusercontent.com/54936003/115510303-c00a3800-a2a9-11eb-99dd-48f2f5c3cbae.png)

**Comment by irzafaikar** [comment]
I'm sorry, this is css issue. I set the style to this one.
![Screenshot-20210422024131-256x126](https://user-images.githubusercontent.com/54936003/115611535-668b2300-a314-11eb-9fb3-a6c1c40c9cf2.png)

**Comment by sandanat** [comment]
Hi @irzafaikar !
Yes, your solution works fine.
However a package already has a [height 100%](https://github.com/sandanat/vue-pdf-app/blob/master/src/sass/viewer.scss#L25)
So it is better to specify a height of parent container
```vue
<template>
  <div style="height: 100vh">
    <vue-pdf-app />
  </div>
</template>
```

Or specify a height directly
```vue
<template>
  <vue-pdf-app style="height: 100vh" />
</template>
```

Explanation is in this [discussion](https://github.com/sandanat/vue-pdf-app/issues/14)
