### ISSUE TITLE
No pdf loaded when using locale file

### ISSUE THREAD

**Issue by stingwear** [sandanat/vue-pdf-app#45]
#### Configuration:
- Web browser and it`s version:
- Operating system and it`s version:
- vue-pdf-app version: 2.0.0

#### Steps to reproduce the problem:

1. Include link to locale file (different than English) in head
2. Create two buttons that loads different pdf files in the same vue using a data variable to store the pdf path
3. Initially the first PDF loads correctly but when we press the second button to load the second PDF, it no longer loads.

#### What is the expected behavior?

The vue-pdf-app should loads the pdf file always

#### What went wrong?

if we include the locale file, the viewer doesn't load the pdf's after the first load.

**Comment by sandanat** [comment]
Hi!
I've tried to reproduce the issue [here](https://github.com/sandanat/vue-pdf-app/tree/bug/task-45/examples/the-most-complete-example/public). Everything works fine.
So provide a working example with your issue. I'll check it out

**Comment by stingwear** [comment]
Hi @sandanat 

I've changed a little bit your example to try to reproduce the bug. 

First of all, I've included a loading var, because in our system, the pdf url is received in a request, then to simulate the request, I add a time interval in the vue:

`<template>
  <div style="height: 80vh;">
    <button @click="changePdf('sample.pdf')" type="button">First pdf</button>
    <button @click="changePdf('second-sample.pdf')" type="button">Second pdf</button>
    <vue-pdf-app v-if="!loading" :pdf="pdf" @pages-rendered="pdfPagesRendered"></vue-pdf-app>
    <p v-else>Loading PDF...</p>
  </div>
</template>

<script>
// VuePdfApp component is registered in src/main.js

export default {
  name: "Basic",
  data() {
    return { 
      pdf: 'sample.pdf',
      loading: false
    };
  },
  methods: {
    changePdf(pdf) {
      this.loading = true;
      setTimeout(() => {
        this.pdf = pdf;
        this.loading = false;        
      }, 3000);
    },
    pdfPagesRendered(pdfApp) {
      pdfApp.pdfViewer.currentScaleValue = 'page-width';
    }
  }
};
</script>`

I share with you a screen recording where you can see how the viewer doesn't load the second PDF at the first click, but then it loads:

[screen recording](https://share.vidyard.com/watch/h8pfgc3MTKJ4g4XaVY8V9U?)

I hope it will be useful. If you need anything else, please let me know.

Regards

**Comment by stingwear** [comment]
Hi again @sandanat 

Is it possible that the problem with the load of the different pdf's with locale files will be that the pdf sources are  in base64 format?

Regards

**Comment by sandanat** [comment]
I don't think so

**Comment by henrik-peszlen** [comment]
First of all, thanks for a great plugin!

I just want to add that I have the exact same problem, using PdfViewer in different tabs and when I'm using locales it only loads the first time. After that I get warnings and the pdf is not rendered.

![image](https://user-images.githubusercontent.com/84004462/117769014-74f19e00-b233-11eb-9de5-e314c3f93f51.png)

All works fine if I remove the locale file.

**Comment by sandanat** [comment]
Sorry for the long wait.

@stingwear, I reproduced your code - everything still works fine. I've tried with IE11, Edge, Firefox, Chrome, network and CPU slowdown - everything is fine. Which browser and OS do you have? Take an example from [this branch](https://github.com/sandanat/vue-pdf-app/blob/bug/task-45/examples/the-most-complete-example/src/views/Basic.vue) and try to check if it works. Please provide a git repo with your example not working.

@henrik-peszlen, I would also ask you to provide a repo with your example. It's hard to identify an error. Errors you provided usually occur when locale file is corrupted or not fully implemented. Where is a `<link>` tag for locale file situated? It is better to place it in a `<head>` tag.

**Comment by henrik-peszlen** [comment]
@sandanat Thanks for your reply, I was able to get it to work when I was making a bare minimum example, some other component or package is probably the culprit in my case. I will investigate some on my end. Thanks.

**Comment by henrik-peszlen** [comment]
I think I found the problem, when I pre-fetch the PDF and pass it in as an arrayBuffer the locale don't work (the second time) but if I pass the file path it works as expected. Maybe this can be of help to someone else.

**Comment by sandanat** [comment]
@henrik-peszlen, locale does not depend on the way pdf is loaded. No errors must occur if locale `link` tag is static (i.e. placed under `head` tag) or is binded to an html document before vue-pdf-app. So reproduce example is needed for further investigation. 
Regards!

**Comment by sandanat** [comment]
@henrik-peszlen, @stingwear, were you able to fix problems? Can I close the issue?

**Comment by henrik-peszlen** [comment]
@sandanat My issue is resolved, thanks.

**Comment by sebarswee** [comment]
> I think I found the problem, when I pre-fetch the PDF and pass it in as an arrayBuffer the locale don't work (the second time) but if I pass the file path it works as expected. Maybe this can be of help to someone else.

I have the same problem using ArrayBuffer, and if I pass  the pdf path or not using locale resource, everything works fine
