### ISSUE TITLE
The loading bar (progress bar) is displayed only for the first time

### ISSUE THREAD

**Issue by This420** [sandanat/vue-pdf-app#48]
#### Configuration:
- Web browser and it`s version: All
- Operating system and it`s version: All
- vue-pdf-app version: 2.0.0

#### Steps to reproduce the problem:
- First, display the pdf in the normal procedure. (At this time, the loading bar is displayed)
- When I go to another page and view the PDF again, the loading bar does not appear. (I'm viewing the PDF in a dialog)

#### What is the expected behavior?
- A loading bar is displayed each time.

**Comment by sandanat** [comment]
Please provide a working example

**Comment by This420** [comment]
@sandanat 
Thank you for your reply.

I found the same issue in the pdf.js repository.

https://github.com/mozilla/pdf.js/issues/3090

Is this solution applicable to vue-pdf-app?
Please let me know if you know the solution.

**Comment by sandanat** [comment]
Yes, I think it can help.
