### ISSUE TITLE
removePageBorders pass option

### ISSUE THREAD

**Issue by dmitriy-pisarevskiy** [sandanat/vue-pdf-app#57]
Hi! How I can pass "true" value to removePageBorders ? or how to set hPadding  and vPaddin to 0?
on this depended calculation:
          widthScale = (this.container.clientWidth - hPadding) / width / _ui_utils.CSS_UNITS;
          heightScale = (this.container.clientHeight - vPadding) / height / _ui_utils.CSS_UNITS;

Version 2.1.0

**Comment by dmitriy-pisarevskiy** [comment]
so, maybe closed, because I already forked this solution. Thanks you, very useful.

**Comment by sandanat** [comment]
Thanks!
