### ISSUE TITLE
Search results positioning problem when searching in findbar

### ISSUE THREAD

**Issue by wongself** [sandanat/vue-pdf-app#58]
#### Configuration:
- Web browser and it`s version: Microsoft Edge 91.0.864.48 & Firefox 89.0.1
- Operating system and it`s version: Windows 10 21H1
- vue-pdf-app version: 2.1.0

#### Steps to reproduce the problem
In the official [demo](https://codesandbox.io/s/vue-2-vue-pdf-app-wz5kv), when you search in the findbar, the results are always positioned in the top row of the page, not in the middle of the page, which is not in line with user habits. At the same time, the horizontal scrollbar does not change with the positioning of the results, so that the search results may not be visible in the current view. In this case, the search results can only be found by manually moving the horizontal scroll bar.

#### What is the expected behavior?
I want the search results to be positioned more friendly when searching in the findbar, the vertical scrollbar can move to make the highlighted field located in the middle of the page, at the same time the horizontal scrollbar can also move to make the highlighted field located in the middle of the page, as the PDF reader in the attachment does.

#### What went wrong?
See above. Not only in the official demo, but also in my own project, I have this search result positioning problem, which greatly affects the search experience.

#### Attachments (screenshots, links, etc)
What I expected:
![Others](https://i.imgur.com/y3zIyID.png)

What I experienced:
![Now](https://i.imgur.com/ZvU3LK3.png)

**Comment by sandanat** [comment]
Hi!
This is a pdfjs problem. I submitted an [issue to the pdfjs](https://github.com/mozilla/pdf.js/issues/13596).
However even if they fix it I will not upgrade pdfjs version for this package as it will break IE11 support (discussion is [here](#47)).
New version of the pdfjs will be included for a package for Vue 3.
