### ISSUE TITLE
Changing page title.

### ISSUE THREAD

**Issue by SkuljAnze** [sandanat/vue-pdf-app#7]
Does anyone have any ideas on how to stop vue-pdf-app from changing the page title?

**Comment by sandanat** [comment]
I'm not sure it's a bug. That is a default behaviour of pdfjs and someone could find this useful. You can reassign page title via open listener
```
<vue-pdf-app @open="openHandler" />

...
openHandler(pdfApp) {
  pdfApp.setTitle(pageTitle);
}
...
```
However a flash occurs during reassign `original title => pdf title => original title`
See [example](https://github.com/sandanat/vue-pdf-app/blob/master/examples/pdfjs-interaction/src/App.vue#L35)

**Comment by sandanat** [comment]
There is another solution:
```js
<vue-pdf-app @open="openHandler" />
...
openHandler(pdfApp) {
      pdfApp.isViewerEmbedded = true;
}
```
