### ISSUE TITLE
showing only one page of pdf file

### ISSUE THREAD

**Issue by Sulaiman-SM** [sandanat/vue-pdf-app#79]
**Please describe a feature/problem.**
I have use case where I only want to open one specific page instead of the entire pdf file and not allow the user to change it

**Describe the solution you'd like**
Either to show only one page instead of the entire pdf or to hide the scrollbar and disable scrolling functionality

**Describe alternatives you've considered**
I have tried to hide the scrollbar and disable the scrolling functionality, I think I need to try more

**Comment by sandanat** [comment]
Hi, this can't be done within this package. You can use **vue-pdf** package, this [example](https://www.npmjs.com/package/vue-pdf#user-content-example---current-page--page-count)

**Comment by Sulaiman-SM** [comment]
Thanks, great work by the way @sandanat
